I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: could not find label 'volunteerSelf'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/nish/script.rpyc", line 83, in script
  File "/usr/share/renpy/renpy/ast.py", line 1519, in execute
    rv = renpy.game.script.lookup(target)
  File "/usr/share/renpy/renpy/script.py", line 843, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'volunteerSelf'.

Linux-4.4.1-2-ARCH-x86_64-with-glibc2.2.5
Ren'Py 6.99.8.959
Polymorphism 0.0
